# https://starship.rs/config/
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$time\
(\\[$username$hostname\\] )\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$status\
$jobs\
$character"""

[time]
disabled = false
format = '[\[[$time]($style)\] ](white)'
style = "#FFD6EC"

[username]
format = "[$user]($style)"
style_user = "bold #E0BFB8"
show_always = false

[hostname]
format = "@[$hostname]($style)"
style = "bold #B8FAEF"
ssh_only = true

[directory]
style = "#FFD9ED"
truncation_symbol = "…/"
truncation_length = 6
read_only = ' -'
#fish_style_pwd_dir_length = 3

[character]
success_symbol = "[❯](#ffd2d2)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[($conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "white"

[status]
disabled = false
pipestatus = true
format = "[$status]($style) "
style = "bold red"
success_style = "white"
pipestatus_format = '\[$pipestatus\]( → [$common_meaning$signal_name$maybe_int]($style)) '
